// src/lib/components/command-menu.svelte
<script lang="ts">
	import { _ } from 'svelte-i18n'
	import {
		Dialog,
		DialogOverlay,
		DialogTitle,
		DialogDescription,
	} from '@rgossiaux/svelte-headlessui'
	import {
		Sailboat,
		BrandGithub,
		BrandTwitter,
		Home,
		Notebook,
		Palette,
		Search,
		FileDescription,
	} from 'tabler-icons-svelte'
	import { commandMenuIsOpen } from '$lib/store'
	import rawThemes from '../../themes.json'

	interface Item {
		icon: any
		name: string
		url: string
		shortname?: string
		description?: string
	}

	let query = ''

	let pages: Item[] = []
	$: pages = [
		{ name: $_('page.home.nav'), url: '/', icon: Home },
		{ name: $_('page.themes.nav'), url: '/themes', icon: Sailboat },
		{ name: $_('page.palette.nav'), url: '/palette', icon: Palette },
		{ name: 'Docs', url: '/docs', icon: FileDescription },
	]

	const socials: Item[] = [
		{
			name: 'GitHub',
			url: 'https://github.com/rose-pine',
			icon: BrandGithub,
		},
		{
			name: 'Twitter',
			url: 'https://twitter.com/rosepinetheme',
			icon: BrandTwitter,
		},
	]

	const matchDomain = /(?:[\w-]+\.)+[\w-]+/
	const themes: Item[] = rawThemes.map(({ name, shortname, repo }) => ({
		name,
		shortname: shortname || '',
		description: repo.includes('github.com')
			? `on GitHub`
			: `on ${repo.match(matchDomain)}`,
		url: repo,
		icon: Notebook,
	}))

	type Group = { name: string; items: Item[] }

	let groups: Group[] = []
	$: groups = [
		{ name: $_('global_search.heading.pages'), items: pages },
		{ name: $_('global_search.heading.themes'), items: themes },
		{ name: $_('global_search.heading.social'), items: socials },
	]

	// Return limited number of items when there is no query
	$: filteredGroups = groups.map((group) => {
		let workingGroup = { ...group }
		workingGroup.items =
			workingGroup.items.filter((item, i) =>
				query
					? item.name.toLowerCase().includes(query.toLowerCase()) ||
					  item.shortname?.toLowerCase().includes(query.toLowerCase())
					: i < 9
			) || []

		return workingGroup
	})

	$: hasResults =
		filteredGroups.filter((group) => group.items.length > 0).length > 0
</script>

<svelte:window
	on:keydown={(e) => {
		// Toggle command palette via keyboard shortcut
		if ((e.ctrlKey || e.metaKey) && e.key === 'k') {
			e.preventDefault()
			commandMenuIsOpen.set(!$commandMenuIsOpen)
		}
	}}
/>

<Dialog
	open={$commandMenuIsOpen}
	on:close={() => commandMenuIsOpen.set(false)}
	class="fixed inset-0 z-20 overflow-y-auto p-4 pt-[25vh]"
>
	<DialogOverlay class="fixed inset-0 bg-zinc-900/50" />

	<DialogTitle class="sr-only">
		{$_('global_search.title')}
	</DialogTitle>

	<DialogDescription class="sr-only">
		{$_('global_search.description')}
	</DialogDescription>

	<div
		class="relative mx-auto max-w-md divide-y overflow-hidden rounded-xl border bg-surface shadow-lg"
	>
		<div class="flex items-center px-4">
			<label for="search">
				<Search size={18} color="hsl(var(--color-subtle))" />
			</label>
			<input
				id="search"
				bind:value={query}
				class="h-12 w-full border-0 bg-transparent px-2 text-sm placeholder-subtle focus:outline-none"
				placeholder={`${$_('global_search.search.label')}...`}
			/>
		</div>

		{#if hasResults}
			<ul class="max-h-96 overflow-y-auto py-4 text-sm">
				{#each filteredGroups as group}
					{#if group.items.length > 0}
						<h3
							class="px-4 pt-4 pb-2 text-xs font-semibold text-subtle first:pt-0"
						>
							{group.name}
						</h3>

						{#each group.items as item}
							<li class="px-2">
								<a
									href={item.url}
									target={item.url.includes('http') ? '_blank' : ''}
									class="group flex items-center space-x-1 rounded px-2 py-2 hover:bg-muted/10 focus:outline-none focus:ring-2"
								>
									<div class="pr-1">
										<svelte:component
											this={item.icon}
											size={18}
											color="hsl(var(--color-subtle))"
										/>
									</div>
									<span class="font-medium">
										{item.name}
									</span>
									{#if item.description}
										<span class="text-subtle">
											{item.description}
										</span>
									{/if}
								</a>
							</li>
						{/each}
					{/if}
				{/each}
			</ul>
		{/if}

		{#if query.length && !hasResults}
			<p class="p-4 text-sm text-subtle">{$_('global_search.search.empty')}</p>
		{/if}
	</div>
</Dialog>

// src/components/command-menu.tsx
import React from "react";
import { Command } from "cmdk";
import {
	IconBrandDiscordFilled,
	IconBrandGithubFilled,
	IconBrandTwitterFilled,
	IconChevronRight,
	IconFileDescription,
	IconHome,
	IconNotebook,
	IconPalette,
	IconSailboat,
	IconSalt,
} from "@tabler/icons-react";
import { useStore } from "@nanostores/react";
import { searchIsOpen } from "$store";

const icons = {
	BrandDiscordFilled: IconBrandDiscordFilled,
	BrandGithubFilled: IconBrandGithubFilled,
	BrandTwitterFilled: IconBrandTwitterFilled,
	FileDescription: IconFileDescription,
	Home: IconHome,
	Notebook: IconNotebook,
	Palette: IconPalette,
	Sailboat: IconSailboat,
	Salt: IconSalt,
} as const;

type Item = {
	icon?: keyof typeof icons;
	color?: string;
	name: string;
	href: string;
};

type Group = {
	name: string;
	featuredName?: string;
	items: Item[];
	featuredItems?: Item[];
};

type Props = {
	groups: Group[];
	searchText: string;
	emptyText: string;
	emptyResults: [name: string, href: string][];
};

const CommandMenu = ({
	groups,
	searchText,
	emptyText,
	emptyResults,
}: Props) => {
	const isOpen = useStore(searchIsOpen);
	const [search, setSearch] = React.useState("");

	// Toggle the menu when ⌘K is pressed
	React.useEffect(() => {
		const down = (e: KeyboardEvent) => {
			if (e.key === "k" && e.metaKey) {
				e.preventDefault();
				e.stopPropagation();
				searchIsOpen.set(!searchIsOpen.get());
			}
		};

		document.addEventListener("keydown", down);
		return () => document.removeEventListener("keydown", down);
	}, []);

	function goto(url: string) {
		searchIsOpen.set(false);
		window.location = url;
	}

	return (
		<Command.Dialog
			open={isOpen}
			onOpenChange={searchIsOpen.set}
			label="Global Command Menu"
		>
			<div cmdk-input-container="">
				<Command.Input
					value={search}
					onValueChange={setSearch}
					placeholder={searchText}
				/>

				<button
					onClick={() => searchIsOpen.set(false)}
					className="flex h-7 items-center justify-center rounded-md border border-muted/20 bg-muted/10 px-1.5 text-subtle transition hover:bg-muted/20 focus:outline-none focus:ring"
				>
					<kbd className="pointer-events-none font-mono text-xs font-semibold uppercase">
						esc
					</kbd>
				</button>
			</div>

			<Command.List>
				<div
					aria-hidden="true"
					className="pointer-events-none sticky top-0 h-6 w-full bg-gradient-to-b from-surface/80 to-transparent blur-md"
				/>
				<Command.Empty>
					<p className="text-center text-sm">{emptyText}</p>

					<div className="divide-y overflow-hidden rounded-xl border bg-muted/5">
						{emptyResults.map(([name, href]) => (
							<a
								key={`empty-${name}`}
								href={href}
								className="group flex items-center space-x-2 p-3 text-sm text-subtle transition first:rounded-t-xl last:rounded-b-xl hover:bg-muted/20 focus:outline-none focus:ring focus:ring-inset"
							>
								<span className="transition group-hover:text-text">{name}</span>

								<div className="flex-1" />

								<span className="text-muted transition group-hover:text-text">
									<IconChevronRight size={18} />
								</span>
							</a>
						))}
					</div>
				</Command.Empty>

				{groups.map((group) => (
					<Command.Group
						key={group.name}
						heading={
							search.length > 0 ? group.name : group.featuredName ?? group.name
						}
					>
						{(search.length > 0
							? group.items
							: group.featuredItems ?? group.items
						).map((item) => (
							<Command.Item
								key={`${group.name}-${item.name}`}
								value={`${group.name}-${item.name}`}
								onSelect={() => goto(item.href)}
							>
								<div className="flex h-5 w-5 items-center justify-center text-subtle transition">
									{!!item.icon && React.createElement(icons[item.icon])}
									{!!item.color && (
										<div
											className="h-[18px] w-[18px] rounded-full border"
											style={{ backgroundColor: item.color }}
										/>
									)}
								</div>

								<p className="truncate">{item.name}</p>

								<div className="flex-1" />

								<p className="flex items-center space-x-2 text-muted transition">
									{item.href.startsWith("http") ? (
										<span>{new URL(item.href).hostname}&nbsp;↗</span>
									) : (
										<IconChevronRight size={18} />
									)}
								</p>
							</Command.Item>
						))}
					</Command.Group>
				))}

				<div
					aria-hidden="true"
					className="pointer-events-none sticky bottom-0 -mt-5 h-8 w-full bg-gradient-to-t from-surface/80 to-transparent blur-md"
				/>
			</Command.List>
		</Command.Dialog>
	);
};

export default CommandMenu;
